/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Report {
  'mitreTechniques' : Array<string>,
  'metadata' : ReportMetadata,
  'iocs' : Array<string>,
  'executiveSummary' : string,
  'findings' : Array<string>,
  'threatActors' : Array<ThreatActor>,
}
export interface ReportMetadata {
  'title' : string,
  'date' : Time,
  'author' : string,
}
export interface ThreatActor { 'name' : string, 'description' : string }
export type Time = bigint;
export interface _SERVICE {
  'deleteReport' : ActorMethod<[bigint], undefined>,
  'getAllReports' : ActorMethod<[], Array<Report>>,
  'getReport' : ActorMethod<[bigint], Report>,
  'saveReport' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];