/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ReportMetadata = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'author' : IDL.Text,
});
export const ThreatActor = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Report = IDL.Record({
  'mitreTechniques' : IDL.Vec(IDL.Text),
  'metadata' : ReportMetadata,
  'iocs' : IDL.Vec(IDL.Text),
  'executiveSummary' : IDL.Text,
  'findings' : IDL.Vec(IDL.Text),
  'threatActors' : IDL.Vec(ThreatActor),
});

export const idlService = IDL.Service({
  'deleteReport' : IDL.Func([IDL.Nat], [], []),
  'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getReport' : IDL.Func([IDL.Nat], [Report], ['query']),
  'saveReport' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ReportMetadata = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'author' : IDL.Text,
  });
  const ThreatActor = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Report = IDL.Record({
    'mitreTechniques' : IDL.Vec(IDL.Text),
    'metadata' : ReportMetadata,
    'iocs' : IDL.Vec(IDL.Text),
    'executiveSummary' : IDL.Text,
    'findings' : IDL.Vec(IDL.Text),
    'threatActors' : IDL.Vec(ThreatActor),
  });
  
  return IDL.Service({
    'deleteReport' : IDL.Func([IDL.Nat], [], []),
    'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getReport' : IDL.Func([IDL.Nat], [Report], ['query']),
    'saveReport' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };