/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Connection {
  'color' : string,
  'sourceId' : string,
  'connectionType' : string,
  'targetId' : string,
}
export interface DiagramState {
  'lines' : Array<Line>,
  'lastModified' : bigint,
  'connections' : Array<Connection>,
  'textLabels' : Array<TextLabel>,
  'icons' : Array<Icon>,
  'freehandDrawings' : Array<FreehandDrawing>,
}
export interface FreehandDrawing {
  'color' : string,
  'strokeWidth' : number,
  'points' : Array<Position>,
}
export interface Icon {
  'id' : string,
  'name' : string,
  'iconType' : string,
  'position' : Position,
}
export interface Line {
  'color' : string,
  'endPosition' : Position,
  'isArrow' : boolean,
  'startPosition' : Position,
  'strokeWidth' : number,
}
export interface NamedDiagram { 'name' : string, 'state' : DiagramState }
export interface Position { 'x' : number, 'y' : number }
export interface TextLabel {
  'content' : string,
  'color' : string,
  'fontWeight' : string,
  'position' : Position,
  'fontSize' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllConnections' : ActorMethod<[bigint], [] | [Array<Connection>]>,
  'getAllDiagrams' : ActorMethod<[], Array<NamedDiagram>>,
  'getAllIconPositions' : ActorMethod<[bigint], [] | [Array<Icon>]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDiagramStateById' : ActorMethod<[bigint], [] | [NamedDiagram]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDiagramState' : ActorMethod<[string, DiagramState], bigint>,
  'updateDiagramName' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];