/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Connection = IDL.Record({
  'color' : IDL.Text,
  'sourceId' : IDL.Text,
  'connectionType' : IDL.Text,
  'targetId' : IDL.Text,
});
export const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const BoxShape = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'color' : IDL.Text,
  'borderWidth' : IDL.Float64,
  'position' : Position,
  'borderColor' : IDL.Text,
  'dimensions' : IDL.Record({ 'height' : IDL.Float64, 'width' : IDL.Float64 }),
});
export const Line = IDL.Record({
  'color' : IDL.Text,
  'endPosition' : Position,
  'isArrow' : IDL.Bool,
  'startPosition' : Position,
  'strokeWidth' : IDL.Float64,
});
export const TextLabel = IDL.Record({
  'content' : IDL.Text,
  'color' : IDL.Text,
  'fontWeight' : IDL.Text,
  'position' : Position,
  'fontSize' : IDL.Float64,
});
export const Icon = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'iconType' : IDL.Text,
  'position' : Position,
});
export const FreehandDrawing = IDL.Record({
  'color' : IDL.Text,
  'strokeWidth' : IDL.Float64,
  'points' : IDL.Vec(Position),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Image = IDL.Record({
  'id' : IDL.Text,
  'file' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Record({ 'height' : IDL.Float64, 'width' : IDL.Float64 }),
  'description' : IDL.Text,
  'position' : Position,
});
export const DiagramState = IDL.Record({
  'boxShapes' : IDL.Vec(BoxShape),
  'lines' : IDL.Vec(Line),
  'lastModified' : IDL.Int,
  'connections' : IDL.Vec(Connection),
  'textLabels' : IDL.Vec(TextLabel),
  'icons' : IDL.Vec(Icon),
  'freehandDrawings' : IDL.Vec(FreehandDrawing),
  'images' : IDL.Vec(Image),
});
export const NamedDiagram = IDL.Record({
  'name' : IDL.Text,
  'state' : DiagramState,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDiagramState' : IDL.Func([IDL.Nat], [], []),
  'getAllConnections' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(Connection))],
      ['query'],
    ),
  'getAllDiagrams' : IDL.Func([], [IDL.Vec(NamedDiagram)], ['query']),
  'getAllIconPositions' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(Icon))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDiagramStateById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(NamedDiagram)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDiagramState' : IDL.Func([IDL.Text, DiagramState], [IDL.Nat], []),
  'updateDiagramName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Connection = IDL.Record({
    'color' : IDL.Text,
    'sourceId' : IDL.Text,
    'connectionType' : IDL.Text,
    'targetId' : IDL.Text,
  });
  const Position = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const BoxShape = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'color' : IDL.Text,
    'borderWidth' : IDL.Float64,
    'position' : Position,
    'borderColor' : IDL.Text,
    'dimensions' : IDL.Record({
      'height' : IDL.Float64,
      'width' : IDL.Float64,
    }),
  });
  const Line = IDL.Record({
    'color' : IDL.Text,
    'endPosition' : Position,
    'isArrow' : IDL.Bool,
    'startPosition' : Position,
    'strokeWidth' : IDL.Float64,
  });
  const TextLabel = IDL.Record({
    'content' : IDL.Text,
    'color' : IDL.Text,
    'fontWeight' : IDL.Text,
    'position' : Position,
    'fontSize' : IDL.Float64,
  });
  const Icon = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'iconType' : IDL.Text,
    'position' : Position,
  });
  const FreehandDrawing = IDL.Record({
    'color' : IDL.Text,
    'strokeWidth' : IDL.Float64,
    'points' : IDL.Vec(Position),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Image = IDL.Record({
    'id' : IDL.Text,
    'file' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Record({ 'height' : IDL.Float64, 'width' : IDL.Float64 }),
    'description' : IDL.Text,
    'position' : Position,
  });
  const DiagramState = IDL.Record({
    'boxShapes' : IDL.Vec(BoxShape),
    'lines' : IDL.Vec(Line),
    'lastModified' : IDL.Int,
    'connections' : IDL.Vec(Connection),
    'textLabels' : IDL.Vec(TextLabel),
    'icons' : IDL.Vec(Icon),
    'freehandDrawings' : IDL.Vec(FreehandDrawing),
    'images' : IDL.Vec(Image),
  });
  const NamedDiagram = IDL.Record({
    'name' : IDL.Text,
    'state' : DiagramState,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDiagramState' : IDL.Func([IDL.Nat], [], []),
    'getAllConnections' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(Connection))],
        ['query'],
      ),
    'getAllDiagrams' : IDL.Func([], [IDL.Vec(NamedDiagram)], ['query']),
    'getAllIconPositions' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(Icon))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDiagramStateById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(NamedDiagram)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDiagramState' : IDL.Func([IDL.Text, DiagramState], [IDL.Nat], []),
    'updateDiagramName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };